---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-deck-patched
description: My personal Bazzite OS image with oberon-governor included.

# base image to build on top of
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable-43 # latest is also supported

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/g/exotic-soc/oberon-governor/repo/fedora-%OS_VERSION%/group_exotic-soc-oberon-governor-fedora-%OS_VERSION%.repo
    install:
      - oberon-governor

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - oberon-governor.service

  - type: signing
