opps:
  frequency:
    min: 350
    max: 2230
  voltage:
    min: 700
    max: 1060
  steps: 24

governor:
  polling_delay_ms: 50
  up_threshold_high: 85
  up_threshold_low: 70
  down_threshold_high: 45
  down_threshold_low: 5
  gfx_temp_soft_lim: 85
  gfx_temp_hard_lim: 90
  soc_temp_hard_lim: 90
  overheat_reset_ms: 10000
